# Starter pipeline
  task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Azure subscription 1(67882e92-6412-4fc5-b9ca-1030aa09d729)'
    azureContainerRegistry: '{"loginServer":"oguzhanaydogan.azurecr.io", "id" : "/subscriptions/67882e92-6412-4fc5-b9ca-1030aa09d729/resourceGroups/container-registry/providers/Microsoft.ContainerRegistry/registries/oguzhanaydogan"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'docker-compose up'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pool:
  vmImage: ubuntu-latest

steps:
